# Spring
spring:
  application:
    name: template
  # spring boot admin
#  boot:
#    admin:
#      client:
#        url: http://localhost:8769
  profiles:
    active: dev
  # 热部署生效
  devtools:
    restart:
      enabled: true

  # mysql
  datasource:
    url: jdbc:mysql://mysql:3306/template
    username: root
    password: root@xleon.site


# logs
logging:
  config: classpath:logback/config.xml

# JWT
jwt:
  secret: R3F5k2Qe2LGNQnoU1/edoeK4Rky04iT777nntorlsMg=
  # 过期时间分钟
  expiry: 30

# actuator
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#  endpoint:
#    health:
#      show-details: always
