# Spring
spring:
  # mysql
  datasource:
    url: jdbc:mysql://mysql:3306/template
    username: root
    password: root@xleon.site

# JWT
jwt:
  secret: R3F5k2Qe2LGNQnoU1/edoeK4Rky04iT777nntorlsMg=
  # 过期时间分钟
  expiry: 3000
